[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons
#/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$5nzP.R8DYAwBACCk9L43pg$c.4Y6MgFAl6EXatQBvyircoUqJ9D6Igs3ZTw7XMrVo1W8NgIYHWd1eZqKPbOipjey6QjqsHoKIqeaqZo7SPTIg

; ================= DATABASE (AIVEN) =================
db_host = %(DB_HOST)s
db_port = %(DB_PORT)s
db_user = %(DB_USER)s
db_password = %(DB_PASSWORD)s
db_name = %(DB_NAME)s
db_sslmode = require

db_maxconn = 20
list_db = True
dbfilter = .*

; ================= WEB =================
proxy_mode = True
web.base.url = https://mis-purchasing-management.onrender.com

; ================= PERFORMANCE =================
workers = 1
max_cron_threads = 1

; ================= LOG & DATA =================
data_dir = /tmp/odoo
log_level = info

; ================= OTHER =================
server_wide_modules = base,web