[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

admin_passwd = $pbkdf2-sha512$600000$5nzP.R8DYAwBACCk9L43pg$c.4Y6MgFAl6EXatQBvyircoUqJ9D6Igs3ZTw7XMrVo1W8NgIYHWd1eZqKPbOipjey6QjqsHoKIqeaqZo7SPTIg

; ================= DATABASE =================
db_host = dpg-d752ailm5p6s73ffkjfg-a.oregon-postgres.render.com
db_port = 5432
db_user = misproject_mwvg_user
db_password = IqGUEV8vlPk2HxvnI081dBWGDU1AsvDf
#db_name = misproject_mwvg  

db_maxconn = 64

; ================= WEB =================
proxy_mode = True

; ================= PERFORMANCE =================
workers = 0
max_cron_threads = 0 

; ================= LOG & DATA =================
data_dir = /tmp/odoo
log_level = info

; ================= OTHER =================
list_db = True
server_wide_modules = base,web