[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

admin_passwd = $pbkdf2-sha512$600000$5nzP.R8DYAwBACCk9L43pg$c.4Y6MgFAl6EXatQBvyircoUqJ9D6Igs3ZTw7XMrVo1W8NgIYHWd1eZqKPbOipjey6QjqsHoKIqeaqZo7SPTIg

; ================= DATABASE =================
db_host = aws-1-ap-northeast-1.pooler.supabase.com
db_port = 5432
db_user = postgres.yrtlzzoiufhfazvpdobn
db_password = Tonyphuc12345@

db_sslmode = require
list_db = True
db_maxconn = 20

; ================= WEB =================
proxy_mode = True
web.base.url = https://mis-purchasing-management.onrender.com

; ================= PERFORMANCE =================
workers = 0
max_cron_threads = 0

; ================= LOG & DATA =================
data_dir = /tmp/odoo
log_level = info

; ================= OTHER =================
server_wide_modules = base,web